final List<Map<String, dynamic>> serviceCategories = [
  {"title": "Cleaning", "image": "assets/image2.png"},
  {"title": "Waste Disposal", "image": "assets/image1.png"},
  {"title": "Plumbing", "image": "assets/image3.png"},
  {"title": "Plumbing", "image": "assets/image3.png"},
  {"title": "Cleaning", "image": "assets/image2.png"},
  {"title": "Waste Disposal", "image": "assets/image1.png"},
  {"title": "Plumbing", "image": "assets/image3.png"},
  {"title": "See All", "image": ""},
];
final List<Map<String, dynamic>> homeservices = [
  {"title": "Home Cleaning", "image": "assets/image5.png"},
  {"title": "Carpet Cleaning", "image": "assets/image7.png"},
  {"title": "Sofa Cleaning", "image": "assets/image6.png"},
];
final services = [
  {
    'id': 'service_1',
    'name': 'Bathroom Cleaning',
    'rating': 4.5,
    'orders': 30,
    'duration': '60 Minutes',
    'price': 499.00,
    'image': 'assets/image5.png',
  },
  {
    'id': 'service_2',
    'name': 'Kitchen Cleaning',
    'rating': 4.7,
    'orders': 25,
    'duration': '90 Minutes',
    'price': 699.00,
    'image': 'assets/image5.png',
  },
  {
    'id': 'service_3',
    'name': 'Sofa Cleaning',
    'rating': 4.3,
    'orders': 18,
    'duration': '45 Minutes',
    'price': 399.00,
    'image': 'assets/image5.png',
  },
  {
    'id': 'service_4',
    'name': 'Carpet Cleaning',
    'rating': 4.6,
    'orders': 40,
    'duration': '120 Minutes',
    'price': 999.00,
    'image': 'assets/image5.png',
  },
  {
    'id': 'service_5',
    'name': 'Window Cleaning',
    'rating': 4.2,
    'orders': 15,
    'duration': '50 Minutes',
    'price': 349.00,
    'image': 'assets/image5.png',
  },
  {
    'id': 'service_6',
    'name': 'Deep House Cleaning',
    'rating': 4.8,
    'orders': 50,
    'duration': '180 Minutes',
    'price': 1999.00,
    'image': 'assets/image5.png',
  },
  {
    'id': 'service_7',
    'name': 'Car Cleaning',
    'rating': 4.4,
    'orders': 22,
    'duration': '90 Minutes',
    'price': 799.00,
    'image': 'assets/image5.png',
  },
  {
    'id': 'service_8',
    'name': 'Mattress Cleaning',
    'rating': 4.1,
    'orders': 12,
    'duration': '60 Minutes',
    'price': 599.00,
    'image': 'assets/image5.png',
  },
  {
    'id': 'service_9',
    'name': 'Pest Control',
    'rating': 4.7,
    'orders': 35,
    'duration': '120 Minutes',
    'price': 1499.00,
    'image': 'assets/image5.png',
  },
  {
    'id': 'service_10',
    'name': 'Garden Cleaning',
    'rating': 4.3,
    'orders': 20,
    'duration': '150 Minutes',
    'price': 899.00,
    'image': 'assets/image5.png',
  },
];
